### ISSUE TITLE
SyntaxError: Unexpected token *

### ISSUE THREAD

**Issue by jlsuarezs** [adamdossa/OxTokenICO#1]

**Comment by adamdossa** [comment]
Possibly you are using an old version of javascript?

The exponentiation operator (**) is part of the ES2016 standard:
http://2ality.com/2016/02/exponentiation-operator.html

You could modify the code to use .pow() instead, or upgrade to a later version of javascript.

**Comment by jlsuarezs** [comment]
Hhumm, not sure. I am just using the truffle framework to build without success...

**Comment by adamdossa** [comment]
You'd need to update to the latest version of node.

________________________________
